language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t feed -f udagram-api-feed/Dockerfile .
  - docker tag feed yk1999/udagram-api-feed:latest
  - docker build -t users -f udagram-api-users/Dockerfile .
  - docker tag users yk1999/udagram-api-users:latest
  - docker build -t udagram-frontend -f udagram-frontend/Dockerfile .
  - docker tag udagram-frontend yk1999/udagram-frontend:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push yk1999/udagram-api-feed
  - docker push yk1999/udagram-api-users
  - docker push yk1999/udagram-frontend